apiVersion: v1
data:
{{- if and .Values.qbittorrent.vpn.enabled (eq .Values.qbittorrent.vpn.type "gluetun") (not .Values.qbittorrent.vpn.gluetun.secret.existing) }}
    {{ .Values.qbittorrent.vpn.gluetun.secret.privateKeySecretKey }}: {{ .Values.qbittorrent.vpn.gluetun.secret.privateKey }}
    {{ .Values.qbittorrent.vpn.gluetun.secret.addressesSecretKey }}: {{ .Values.qbittorrent.vpn.gluetun.secret.addresses }}
{{- end }}
{{- if and .Values.qbittorrent.vpn.enabled (eq .Values.qbittorrent.vpn.type "tailscale") (not .Values.qbittorrent.vpn.tailscale.secret.existing) }}
    {{ .Values.qbittorrent.vpn.tailscale.secret.tokenKey }}: {{ .Values.qbittorrent.vpn.tailscale.secret.token }}
{{- end }}
{{ if not .Values.discord.secret.existing }}
    {{ .Values.discord.secret.tokenSecretKey }}: {{ .Values.discord.secret.token }}
{{ end }}
kind: Secret
metadata:
  name: arr-secret
  namespace: {{ .Release.Namespace }}